---
output:
  pdf_document: default
  html_document: default
header-includes:
  - \usepackage{graphicx}
---

```{r setup, include=FALSE}
lapply(c("tidyverse", "cancensus", "knitr", "readr", "sf", 
         "geojsonsf", "paletteer", "kableExtra", 
         "broom", "here", "stargazer"), library, character.only = TRUE)
```

## Census data

We load previously loaded census data. The code for fetching this data is also shown in this section.

```{r, eval = FALSE}
#| execute: false
load(here("API_KEY.rda"))

options(cancensus.api_key = api_key)
options(cancensus.cache_path = "cache")

vectors <- c("v_CA21_1", "v_CA21_6", "v_CA21_452", "v_CA21_449", "v_CA21_1040", "v_CA21_1085", "v_CA21_905")

region_DA <- c("59154012", "59154105", "59154090", "59150936", "59154101", "59154104", 
               "59154035", "59154103", "59154102", "59154034", "59150945", "59154091", 
               "59154093", "59154099", "59150946", "59154100", "59154078", "59154079", 
               "59154082", "59154081", "59154080", "59150939", "59150938", "59154083", 
               "59154095", "59154084", "59150941", "59150942", "59154085", "59154088", 
               "59154087", "59154089", "59154097", "59154098", "59154096", "59154092", 
               "59154013", "59150952")

census_data <- get_census(
  dataset = "CA21",
  regions = list(CSD = "5915022", DA = region_DA),
  vectors = vectors,
  labels = "detailed",
  geo_format = "sf",
  level = "DA"
)

census_data <- census_data %>%
  mutate(pop_density = `v_CA21_1: Population, 2021` / `Shape Area`)

can_api_key <- ""
save(census_data, file = "../../data/census.rda")
```

```{r table_1}
load(here("data/census.rda"))

n <- nrow(census_data)
kable(head(census_data[, 1:5]), format = "latex", booktabs = TRUE, caption = "Census Data, 2021 (truncated rows and columns)") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```

## Food data

```{r}
food_data <- st_read(here("data/free-and-low-cost-food-programs.shp"))  %>%
  select(
    "program_nam",
    "program_sta",
    "meal_cost",
    "local_areas",
    "latitude",
    "longitude",
    "geometry"
  ) %>%
  drop_na("latitude", "longitude") %>%
  # set to wgs 84 as per can census
  st_set_crs(4326)
```

```{r table_2}
# Food data processing
food_count <- food_data %>%
  st_set_geometry(NULL) %>% 
  group_by(local_areas) %>%
  summarise(count = n(), .groups = "drop")

food_data_count <- food_data %>%
  left_join(food_count, by = "local_areas") %>%
  distinct(local_areas, .keep_all = TRUE) # one row per neighbourhood

combo_food_census <- census_data %>%
  st_join(food_data_count)

census_data_food <- combo_food_census %>%
  mutate(program_count = replace_na(count, 0),
         food_density = program_count / `Shape Area`)

head(census_data_food[, 1:5]) %>%
  kable(format = "latex", booktabs = TRUE, caption = "Food Data merged with Census Data, 2021 (truncated rows and columns)") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```

\_

## Crime data

```{r}
crime <- read_csv(here("data/crime_data_all_neighborhoods.csv"), show_col_types = FALSE) %>%
  mutate(TYPE = as_factor(TYPE),
         HUNDRED_BLOCK = as_factor(HUNDRED_BLOCK),
         NEIGHBOURHOOD = as_factor(NEIGHBOURHOOD)) %>%
  filter(!is.na(X) & !is.na(Y))

crime_data <- st_as_sf(crime, coords = c("X", "Y"), crs = "+proj=utm +zone=10") %>%
  st_transform(crs = "+proj=longlat +datum=WGS84")
```

```{r}
intersections <- st_is_within_distance(census_data, crime_data, sparse = FALSE, dist = 5)

crimes_contained <- rowSums(intersections, dims = 1)

census_data_crime <- census_data %>%
  cbind(crimes_contained) %>%
  mutate(crime_density = crimes_contained / Shape.Area)

unique_crimes <- unique(crime_data$TYPE)

for (type in unique_crimes) {
  type_data <- crime_data %>% filter(TYPE == type)
  intersections <- st_is_within_distance(census_data, type_data, sparse = FALSE, dist = 5)
  sum <- rowSums(intersections, dims = 1)
  df <- as.data.frame(sum)
  census_data_crime <- census_data_crime %>% cbind(df$sum) %>% rename_with(~ paste0("crimes_", type), df.sum)
}
```

## Training data

Now we merge all of our data-sets into one table so we can feed it into our model.

```{r}
training_data <- st_join(census_data_crime, census_data_food)

training_data <- training_data %>%
  rename_with(
    ~ gsub(":.*$", "", .),  # Remove everything after the colon, including the colon
    starts_with("v_CA21")  # Apply only to columns starting with "v_CA21"
  )

median_lico_at <- median(training_data$v_CA21_1085, na.rm = TRUE)

training_data <- training_data %>%
  mutate(
    low_income = ifelse(
      v_CA21_1085 > median_lico_at, 
      1, 
      0))


training_data[is.na(training_data)] <- 0
```

# Model

## Specification

```{r}
# Specification models
# 1. Model with all variables (including interaction term)
reg_all_vars <- lm(crime_density ~ 
                   food_density:low_income + 
                   food_density + 
                   pop_density.x + 
                   v_CA21_452 +
                   low_income, 
                 data = st_set_geometry(training_data, NULL))

# 2. Model without the interaction term
reg_no_interaction <- lm(crime_density ~ 
                         food_density + 
                         pop_density.x + 
                         v_CA21_452 +
                         low_income, 
                       data = st_set_geometry(training_data, NULL))

# 3. Model with only food density, crime density, and low income
reg_food_crime_low_income <- lm(crime_density ~ 
                                food_density + 
                                low_income, 
                              data = st_set_geometry(training_data, NULL))

# 4. Model with all variables (including interaction term) but replacing v_CA21_452 with v_CA21_449
reg_all_vars_449 <- lm(crime_density ~ 
                       food_density:low_income + 
                       food_density + 
                       pop_density.x + 
                       v_CA21_449 +  # Replaced v_CA21_452 with v_CA21_449
                       low_income, 
                     data = st_set_geometry(training_data, NULL))

models_spec <- list(
  "All Variables" = reg_all_vars,
  "Without Interaction" = reg_no_interaction,
  "Food Density, Crime, Low Income" = reg_food_crime_low_income
)

# Summary for each specification tested
summary_all_vars <- summary(reg_all_vars)
summary_no_interaction <- summary(reg_no_interaction)
summary_food_crime_low_income <- summary(reg_food_crime_low_income)
summary_all_vars_449 <- summary(reg_all_vars_449)

# Add to the list of model summaries
model_summaries <- list(
  "All Variables" = summary_all_vars,
  "Without Interaction" = summary_no_interaction,
  "Food Density, Crime, Low Income" = summary_food_crime_low_income,
  "All Variables (with v_CA21_449)" = summary_all_vars_449
)
```

# RESULTS FROM SPEC

```{r, results="asis"}
stargazer(
  reg_all_vars,
  reg_no_interaction, 
  reg_food_crime_low_income,
  type = "latex",
  covariate.labels = c(
    "(Intercept)",
    "Food Program Density: Low Income",
    "Food Program Density",
    "Population Density", 
    "Average Household Size (v\\_CA21\\_452)",
    "Low Income"
    
  ),
  omit = c("pop_density.x", "v_CA21_452"),
  add.lines = list(
    c("Includes Interaction?", "Yes", "No", "No"),
    c("Population Density Included?", "Yes", "Yes", "No"), 
    c("Average Household Size (v\\_CA21\\_452) Included?", "Yes", "Yes", "No")
  ),
  title = "Regression Specification Table",
  digits = 3
)
```

### Model 1: 

```{r, results='asis'}
# Model 1: reg_all_vars
stargazer(reg_all_vars, type = "latex",
          covariate.labels = c("(Intercept)", 
                              "Food Program Density: Low Income",
    "Food Program Density",
    "Population Density", 
    "Average Household Size (v\\_CA21\\_452)",
    "Low Income"),
          add.lines = list(
            c("Includes Interaction?", "Yes", "No", "No"),
            c("Population Density Included?", "Yes", "Yes", "No"),
            c("Average Household Size (v\\_CA21\\_452) Included?", "Yes", "Yes", "No")
          ),
          title = "Spec 1: All Variables",
          digits = 3)
```

### Model 2:

```{r, results='asis'}
# Model 2: reg_no_interaction
stargazer(reg_no_interaction, type = "latex",
          covariate.labels = c("(Intercept)",
                              "Food Program Density",
                              "Population Density", 
                              "Average Household Size (v\\_CA21\\_452)",
                              "Low Income"),
          add.lines = list(
            c("Includes Interaction?", "No", "No", "No"),
            c("Population Density Included?", "Yes", "Yes", "No"),
            c("Average Household Size (v\\_CA21\\_452) Included?", "Yes", "Yes", "No")
          ),
          title = "Spec 2: Omitted interaction term",
          digits = 3)
```

### Model 3:

```{r, results='asis'}
# Model 3: reg_food_crime_low_income
stargazer(reg_food_crime_low_income, type = "latex",
          covariate.labels = c("(Intercept)",
                              "Food Program Density",
                              "Low Income"),
          omit = c("pop_density.x", "v_CA21_452"),
          add.lines = list(
            c("Includes Interaction?", "No", "No", "No"),
            c("Population Density Included?", "No", "Yes", "No"), 
            c("Average Household Size (v\\_CA21\\_452) Included?", "No", "Yes", "No")
          ),
          title = "Spec 3: Food Density and Low Income",
          digits = 3)
```

```{r, results='asis'}
stargazer(reg_all_vars_449,
          type = "latex",
          covariate.labels = c("Food Program Density: Low Income", 
                               "Food Program Density", 
                               "Population Density", 
                               "Persons in Household (v\\_CA21\\_449)", 
                               "Low Income"),
          dep.var.labels = "Crime Density",
          title = "Regression Model Summary (with Persons in Household)",
          digits = 3)
```
